name: mcdsm

services:

  aidax:
    image: aidax:latest
    build: .
    ports:
      - 8000:8000
    environment:
      - "OLLAMA_URL=${OLLAMA_URL}"
      - "OLLAMA_MODEL=${OLLAMA_MODEL}"
      - "OLLAMA_AUTH_USER=${OLLAMA_AUTH_USER}"
      - "OLLAMA_AUTH_PASS=${OLLAMA_AUTH_PASS}"
