# syntax=docker/dockerfile:1

FROM python:3.12-slim

WORKDIR /api

# Install requirements generated by Poetry using pip3
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy Quart app files into container
COPY app/ app/

EXPOSE 8000

# Serve Quart app with Hypercorn ASGI server
ENTRYPOINT [ "hypercorn", "app:app" ]
CMD [ "--bind", "0.0.0.0:8000" ]
